language: java
install: true
jdk: oraclejdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
  - $HOME/.sonar/cache/
before_script:
  - ./gradlew --no-daemon --version
script: ./gradlew --console=plain --no-daemon clean build jacocoTestReport
env: TERM=dumb
after_success: ./gradlew --console=plain --no-daemon coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/8d6db2c9eeb9719573e8
    on_success: change
    on_failure: always
    on_start: never